/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006e28",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3f493e",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#002107",
        "primary-container": "#006e28",
        secondary: "#006e28",
        "surface-container-highest": "#d9e6d6",
        "secondary-fixed": "#72fe88",
        surface: "#f0fdec",
        "on-primary-fixed-variant": "#00531c",
        "surface-container": "#e4f2e1",
        "on-secondary-fixed": "#002107",
        "surface-container-high": "#deecdb",
        "secondary-container": "#6ffb85",
        "surface-variant": "#d9e6d6",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f0fdec",
        "tertiary-container": "#9d413d",
        "on-error": "#ffffff",
        "inverse-primary": "#7edb86",
        "inverse-surface": "#283328",
        "inverse-on-surface": "#e7f5e4",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#90ee97",
        "primary-fixed": "#9af8a0",
        "secondary-fixed-dim": "#53e16f",
        primary: "#00531c",
        "outline-variant": "#bfcabb",
        "surface-container-low": "#eaf7e7",
        "on-secondary-container": "#00732a",
        "primary-fixed-dim": "#7edb86",
        "surface-dim": "#d0decd",
        "on-surface": "#131e14",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#410004",
        "on-background": "#131e14",
        outline: "#6f7a6d",
        "on-secondary-fixed-variant": "#00531c",
        background: "#f0fdec",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffcdc9",
        tertiary: "#7e2a28",
        "on-tertiary-fixed-variant": "#7e2a28",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "gutter-bento": "12px",
        "margin-mobile": "16px",
        xl: "32px",
        xs: "4px",
        lg: "24px",
        sm: "8px",
        md: "16px",
      },
      fontFamily: {
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-lg": [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
        "label-sm": [
          "11px",
          {
            lineHeight: "13px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["17px", { lineHeight: "22px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "25px", fontWeight: "600" }],
        "display-lg": [
          "34px",
          {
            lineHeight: "41px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "22px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "body-md": ["15px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
